// /api/cid.js — Busca CID-10 (DATASUS, portugues brasileiro)
// Dados embutidos — sem dependencia de CDN externo. 9a funcao Vercel.
// GET ?q=query ou POST { q: "query" } → { results: [{code, desc}] }

const CID = {
"A00":"Colera","A001":"Colera biotipo cholerae","A009":"Colera nao especificada",
"A01":"Febres tifoide e paratifoide","A010":"Febre tifoide","A019":"Febre paratifoide nao especificada",
"A02":"Infeccoes por Salmonella","A09":"Diarreia e gastroenterite de origem infecciosa",
"A15":"Tuberculose respiratoria","A150":"Tuberculose pulmonar confirmada","A162":"Tuberculose pulmonar sem confirmacao","A17":"Tuberculose do sistema nervoso","A170":"Meningite tuberculosa","A18":"Tuberculose de outros orgaos","A180":"Tuberculose ossea","A181":"Tuberculose urogenital","A182":"Tuberculose ganglionar periferica","A183":"Tuberculose intestinal","A19":"Tuberculose miliar",
"A27":"Leptospirose","A270":"Leptospirose icterohemorragica","A279":"Leptospirose nao especificada",
"A30":"Hanseniase","A300":"Hanseniase indeterminada","A301":"Hanseniase tuberculoide","A302":"Hanseniase borderline tuberculoide","A303":"Hanseniase borderline","A304":"Hanseniase borderline virchowiana","A305":"Hanseniase virchowiana","A309":"Hanseniase nao especificada",
"A39":"Infeccao meningococica","A390":"Meningite meningococica","A391":"Septicemia meningococica",
"A40":"Septicemia por Streptococcus","A41":"Septicemia","A410":"Septicemia por Staphylococcus aureus","A411":"Septicemia por Staphylococcus","A415":"Septicemia gram-negativa","A418":"Outras septicemias","A419":"Septicemia nao especificada",
"A46":"Erisipela",
"A50":"Sifilis congenita","A51":"Sifilis precoce","A510":"Sifilis primaria genital","A513":"Sifilis secundaria","A519":"Sifilis precoce nao especificada","A52":"Sifilis tardia","A521":"Neurossifilis sintomatica","A523":"Neurossifilis nao especificada","A529":"Sifilis tardia nao especificada","A539":"Sifilis nao especificada",
"A54":"Gonorreia","A540":"Gonorreia trato geniturinario inferior","A549":"Gonorreia nao especificada",
"A56":"Clamidiose","A560":"Clamidiose geniturinaria","A569":"Clamidiose nao especificada",
"A59":"Tricomoniase","A590":"Tricomoniase urogenital","A599":"Tricomoniase nao especificada",
"A60":"Herpes anogenital","A600":"Herpes genital","A609":"Herpes anogenital nao especificado",
"A63":"Verrugas anogenitais","A630":"Condiloma acuminado",
"A64":"Doenca sexualmente transmissivel nao especificada",
"A69":"Doenca de Lyme","A692":"Doenca de Lyme",
"A82":"Raiva","A83":"Encefalite por arbovirus","A87":"Meningite viral","A879":"Meningite viral nao especificada",
"A90":"Dengue","A91":"Dengue hemorragica","A920":"Chikungunya","A929":"Febre viral por mosquito nao especificada","A95":"Febre amarela","A950":"Febre amarela silvestre","A951":"Febre amarela urbana",
"A970":"Dengue sem sinal de alarme","A971":"Dengue com sinal de alarme","A972":"Dengue grave",
"B00":"Herpes simples","B000":"Eczema herpeticum","B002":"Gengivostomatite herpetica","B003":"Meningite herpetica","B004":"Encefalite herpetica","B005":"Herpes ocular","B009":"Herpes simples nao especificado",
"B01":"Varicela","B019":"Varicela sem complicacoes","B01":"Varicela com complicacoes",
"B02":"Herpes zoster","B020":"Encefalite por herpes zoster","B022":"Herpes zoster neurologico","B023":"Herpes zoster ocular","B029":"Herpes zoster nao especificado",
"B05":"Sarampo","B059":"Sarampo sem complicacoes","B06":"Rubeola","B069":"Rubeola sem complicacoes",
"B07":"Verrugas virais","B079":"Verruga viral nao especificada",
"B08":"Molusco contagioso","B081":"Molusco contagioso",
"B15":"Hepatite A","B159":"Hepatite A sem coma","B16":"Hepatite B aguda","B169":"Hepatite B aguda nao especificada","B17":"Hepatite viral aguda","B171":"Hepatite C aguda","B18":"Hepatite viral cronica","B180":"Hepatite B cronica com delta","B181":"Hepatite B cronica","B182":"Hepatite C cronica","B188":"Hepatite viral cronica especificada","B189":"Hepatite viral cronica nao especificada",
"B20":"HIV com doenca infecciosa","B21":"HIV com neoplasia","B24":"HIV nao especificado",
"B26":"Caxumba","B269":"Caxumba sem complicacoes",
"B27":"Mononucleose infecciosa","B279":"Mononucleose nao especificada",
"B35":"Tinea","B350":"Tinea capitis","B351":"Onicomicose","B352":"Tinea manus","B353":"Tinea pedis","B354":"Tinea corporis","B355":"Tinea imbricata","B356":"Tinea cruris","B359":"Dermatofitose nao especificada",
"B36":"Micoses superficiais","B360":"Pitiríase versicolor",
"B37":"Candidose","B370":"Candidose oral","B372":"Candidose cutanea","B373":"Candidose vaginal","B374":"Candidose genital masculina","B375":"Meningite por Candida","B377":"Septicemia por Candida","B379":"Candidose nao especificada",
"B41":"Paracoccidioidomicose","B419":"Paracoccidioidomicose nao especificada",
"B44":"Aspergilose","B45":"Criptococose",
"B50":"Malaria por Plasmodium falciparum","B51":"Malaria por Plasmodium vivax","B54":"Malaria nao especificada",
"B55":"Leishmaniose","B550":"Leishmaniose visceral","B551":"Leishmaniose cutanea","B552":"Leishmaniose mucocutanea","B559":"Leishmaniose nao especificada",
"B57":"Doenca de Chagas","B572":"Doenca de Chagas cronica cardiaca","B573":"Doenca de Chagas cronica digestiva","B574":"Doenca de Chagas cronica nervosa",
"B58":"Toxoplasmose","B589":"Toxoplasmose nao especificada",
"B65":"Esquistossomose","B651":"Esquistossomose por S. mansoni","B659":"Esquistossomose nao especificada",
"B77":"Ascaridiase","B80":"Enterobiase","B86":"Escabiose","B87":"Miase",
"C00":"Neoplasia maligna do labio","C01":"Neoplasia maligna da base da lingua",
"C15":"Cancer de esofago","C159":"Neoplasia maligna do esofago nao especificado",
"C16":"Cancer de estomago","C169":"Neoplasia maligna do estomago nao especificado",
"C18":"Cancer de colon","C180":"Cancer do ceco","C182":"Cancer do colon ascendente","C184":"Cancer do colon transverso","C186":"Cancer do colon descendente","C187":"Cancer do colon sigmoide","C189":"Cancer do colon nao especificado",
"C19":"Cancer da juncao retossigmoide","C20":"Cancer de reto","C21":"Cancer do anus",
"C22":"Cancer de figado","C220":"Carcinoma hepatocelular","C221":"Colangiocarcinoma","C229":"Neoplasia maligna do figado nao especificado",
"C23":"Cancer de vesicula biliar","C24":"Cancer das vias biliares","C25":"Cancer de pancreas","C250":"Cancer da cabeca do pancreas","C251":"Cancer do corpo do pancreas","C252":"Cancer da cauda do pancreas","C259":"Cancer de pancreas nao especificado",
"C32":"Cancer de laringe","C33":"Cancer de traqueia",
"C34":"Cancer de pulmao","C341":"Cancer do lobo superior do pulmao","C342":"Cancer do lobo medio do pulmao","C343":"Cancer do lobo inferior do pulmao","C349":"Cancer de pulmao nao especificado",
"C43":"Melanoma maligno","C439":"Melanoma maligno da pele nao especificado",
"C44":"Carcinoma basocelular","C45":"Mesotelioma","C46":"Sarcoma de Kaposi",
"C50":"Cancer de mama","C500":"Cancer do mamilo","C502":"Cancer do quadrante superior interno da mama","C504":"Cancer do quadrante superior externo da mama","C509":"Cancer de mama nao especificado",
"C51":"Cancer de vulva","C52":"Cancer de vagina",
"C53":"Cancer do colo do utero","C530":"Cancer endocervix","C531":"Cancer exocervix","C539":"Cancer do colo do utero nao especificado",
"C54":"Cancer do corpo do utero","C541":"Cancer de endometrio","C549":"Cancer do utero nao especificado",
"C55":"Cancer do utero nao especificado","C56":"Cancer de ovario",
"C61":"Cancer de prostata","C62":"Cancer de testiculo",
"C64":"Cancer de rim","C67":"Cancer de bexiga","C679":"Cancer de bexiga nao especificado",
"C71":"Cancer de encefalo","C719":"Cancer do encefalo nao especificado","C72":"Cancer do sistema nervoso central",
"C73":"Cancer de tireoide","C74":"Cancer de suprarrenal","C75":"Cancer de glandulas endocrinas",
"C81":"Doenca de Hodgkin","C82":"Linfoma nao-Hodgkin folicular","C83":"Linfoma nao-Hodgkin difuso","C85":"Linfoma nao-Hodgkin nao especificado",
"C90":"Mieloma multiplo","C900":"Mieloma multiplo",
"C91":"Leucemia linfoide","C910":"Leucemia linfoide aguda","C911":"Leucemia linfoide cronica",
"C92":"Leucemia mieloide","C920":"Leucemia mieloide aguda","C921":"Leucemia mieloide cronica","C924":"Leucemia promielocitica aguda",
"D05":"Carcinoma in situ da mama","D06":"Carcinoma in situ do colo do utero",
"D17":"Lipoma","D18":"Hemangioma","D22":"Nevo melanocitico","D23":"Tumor benigno da pele","D24":"Tumor benigno da mama","D25":"Leiomioma do utero","D27":"Cisto de ovario","D33":"Tumor benigno do sistema nervoso central","D34":"Adenoma de tireoide","D35":"Tumor benigno de glandulas endocrinas",
"D45":"Policitemia vera","D46":"Sindrome mielodisplasica",
"D50":"Anemia ferropriva","D500":"Anemia por deficiencia de ferro por perda de sangue","D508":"Outras anemias ferroprivas","D509":"Anemia por deficiencia de ferro nao especificada",
"D51":"Anemia por deficiencia de B12","D52":"Anemia por deficiencia de folato","D53":"Outras anemias nutricionais",
"D55":"Anemia enzimatica","D56":"Talassemia","D57":"Anemia falciforme","D570":"Anemia falciforme com crise","D571":"Anemia falciforme sem crise","D578":"Outros transtornos falciformes",
"D59":"Anemia hemolitica adquirida","D60":"Aplasia eritroide pura","D61":"Anemia aplasica","D62":"Anemia aguda pos-hemorragica","D63":"Anemia em doenca cronica","D64":"Outras anemias",
"D65":"Coagulacao intravascular disseminada","D66":"Hemofilia A","D67":"Hemofilia B","D68":"Outros defeitos de coagulacao","D69":"Purpura","D70":"Agranulocitose","D72":"Leucocitose",
"E00":"Hipotiroidismo congenito por deficiencia de iodo","E03":"Hipotiroidismo","E030":"Hipotiroidismo congenito sem bocio","E032":"Hipotiroidismo medicamentoso","E035":"Coma mixedematoso","E039":"Hipotiroidismo nao especificado",
"E04":"Bocio nao toxico","E040":"Bocio difuso nao toxico","E041":"Bocio uninodular nao toxico","E042":"Bocio multinodular nao toxico","E049":"Bocio nao especificado",
"E05":"Hipertiroidismo","E050":"Doenca de Graves","E051":"Bócio toxico uninodular","E052":"Bocio toxico multinodular","E055":"Crise tireotoxica","E059":"Hipertiroidismo nao especificado",
"E06":"Tiroidite","E060":"Tiroidite aguda","E061":"Tiroidite subaguda","E063":"Tiroidite de Hashimoto","E069":"Tiroidite nao especificada",
"E10":"Diabetes mellitus tipo 1","E100":"DM tipo 1 com coma","E101":"DM tipo 1 com cetoacidose","E102":"DM tipo 1 com nefropatia","E103":"DM tipo 1 com retinopatia","E104":"DM tipo 1 com neuropatia","E105":"DM tipo 1 com angiopatia","E109":"DM tipo 1 sem complicacoes",
"E11":"Diabetes mellitus tipo 2","E110":"DM tipo 2 com coma","E111":"DM tipo 2 com cetoacidose","E112":"DM tipo 2 com nefropatia","E113":"DM tipo 2 com retinopatia","E114":"DM tipo 2 com neuropatia","E115":"DM tipo 2 com angiopatia","E116":"DM tipo 2 com outras complicacoes","E117":"DM tipo 2 com complicacoes multiplas","E119":"DM tipo 2 sem complicacoes",
"E14":"Diabetes mellitus nao especificado",
"E16":"Hipoglicemia","E20":"Hipoparatireoidismo","E21":"Hiperparatireoidismo","E22":"Hiperfuncao da hipofise","E230":"Hipopituitarismo","E24":"Sindrome de Cushing","E25":"Sindrome adrenogenital","E26":"Hiperaldosteronismo","E27":"Insuficiencia suprarrenal","E270":"Doenca de Addison",
"E28":"Sindrome dos ovarios policisticos","E289":"Disfuncao ovariana nao especificada",
"E29":"Hipogonadismo masculino",
"E40":"Kwashiorkor","E41":"Marasmo","E43":"Desnutricao proteico-calorica grave","E44":"Desnutricao moderada","E46":"Desnutricao nao especificada",
"E55":"Deficiencia de vitamina D","E56":"Outras deficiencias vitaminicas",
"E66":"Obesidade","E660":"Obesidade exogena","E662":"Sindrome de Pickwick","E669":"Obesidade nao especificada",
"E78":"Dislipidemias","E780":"Hipercolesterolemia","E781":"Hipertrigliceridemia","E782":"Hiperlipidemia mista","E784":"Outras hiperlipidemias","E785":"Hiperlipidemia nao especificada","E788":"Dislipidemia mista","E789":"Dislipidemia nao especificada",
"E79":"Gota","E790":"Hiperuricemia assintomatica","E799":"Transtorno do metabolismo das purinas nao especificado",
"E83":"Transtornos do metabolismo de minerais","E860":"Desidratacao","E870":"Hipernatremia","E871":"Hiponatremia","E872":"Acidose metabolica","E873":"Alcalose metabolica","E875":"Hiperpotassemia","E876":"Hipopotassemia","E879":"Transtorno hidroeletrolitico nao especificado",
"E88":"Sindrome metabolica",
"F00":"Demencia de Alzheimer","F009":"Demencia de Alzheimer nao especificada",
"F01":"Demencia vascular","F019":"Demencia vascular nao especificada",
"F03":"Demencia nao especificada",
"F05":"Delirium","F059":"Delirium nao especificado",
"F10":"Dependencia de alcool","F100":"Intoxicacao aguda por alcool","F101":"Uso nocivo de alcool","F102":"Sindrome de dependencia alcolica","F103":"Abstinencia de alcool","F104":"Delirium tremens",
"F11":"Dependencia de opioides","F12":"Dependencia de cannabinoides","F14":"Dependencia de cocaina","F17":"Dependencia de nicotina","F19":"Dependencia de multiplas drogas",
"F20":"Esquizofrenia","F200":"Esquizofrenia paranoide","F209":"Esquizofrenia nao especificada",
"F25":"Transtorno esquizoafetivo",
"F31":"Transtorno bipolar","F310":"Hipomania","F311":"Mania sem psicose","F312":"Mania com psicose","F313":"Depressao leve em bipolar","F314":"Depressao grave sem psicose em bipolar","F315":"Depressao grave com psicose em bipolar","F316":"Episodio misto bipolar","F319":"Transtorno bipolar nao especificado",
"F32":"Episodio depressivo","F320":"Depressao leve","F321":"Depressao moderada","F322":"Depressao grave sem psicose","F323":"Depressao grave com psicose","F329":"Episodio depressivo nao especificado",
"F33":"Depressao recorrente","F339":"Depressao recorrente nao especificada",
"F34":"Distimia","F341":"Distimia",
"F40":"Fobia","F400":"Agorafobia","F401":"Fobia social","F402":"Fobia especifica","F409":"Fobia nao especificada",
"F41":"Transtorno de ansiedade","F410":"Transtorno do panico","F411":"Ansiedade generalizada","F412":"Transtorno misto ansioso e depressivo","F419":"Transtorno ansioso nao especificado",
"F42":"TOC - Transtorno obsessivo-compulsivo",
"F43":"Estresse e adaptacao","F430":"Reacao aguda ao estresse","F431":"TEPT - Transtorno de estresse pos-traumatico","F432":"Transtorno de adaptacao",
"F44":"Transtorno dissociativo","F45":"Transtorno somatoforme","F450":"Somatizacao","F452":"Hipocondria","F454":"Dor somatoforme","F459":"Transtorno somatoforme nao especificado",
"F50":"Transtorno alimentar","F500":"Anorexia nervosa","F502":"Bulimia nervosa",
"F51":"Insonia","F510":"Insonia nao organica",
"F60":"Transtorno de personalidade","F603":"Borderline - Transtorno de personalidade emocionalmente instavel","F609":"Transtorno de personalidade nao especificado",
"F70":"Deficiencia intelectual leve","F71":"Deficiencia intelectual moderada","F72":"Deficiencia intelectual grave","F79":"Deficiencia intelectual nao especificada",
"F84":"Transtorno global do desenvolvimento","F840":"Autismo infantil","F845":"Sindrome de Asperger",
"F90":"TDAH - Transtorno de deficit de atencao e hiperatividade","F900":"TDAH tipo combinado","F909":"TDAH nao especificado",
"G00":"Meningite bacteriana","G009":"Meningite bacteriana nao especificada",
"G03":"Meningite de outra causa","G04":"Encefalite","G05":"Encefalite em doencas","G06":"Abscesso cerebral",
"G10":"Doenca de Huntington","G20":"Doenca de Parkinson","G21":"Parkinsonismo secundario",
"G30":"Doenca de Alzheimer","G300":"Alzheimer de inicio precoce","G301":"Alzheimer de inicio tardio","G309":"Alzheimer nao especificado",
"G35":"Esclerose multipla",
"G40":"Epilepsia","G400":"Epilepsia focal idiopatica","G403":"Epilepsia generalizada idiopatica","G409":"Epilepsia nao especificada",
"G41":"Estado de mal epileptico",
"G43":"Enxaqueca","G430":"Enxaqueca sem aura","G431":"Enxaqueca com aura","G439":"Enxaqueca nao especificada",
"G44":"Cefaleia","G440":"Cefaleia em salvas","G441":"Hemicrania","G442":"Cefaleia tensional","G449":"Cefaleia nao especificada",
"G45":"Ataque isquemico transitorio","G459":"AIT nao especificado",
"G47":"Transtorno do sono","G470":"Insonia","G471":"Hipersonia","G473":"Apneia do sono","G474":"Narcolepsia","G479":"Transtorno do sono nao especificado",
"G50":"Neuralgia do trigemeo","G51":"Paralisia de Bell","G510":"Paralisia de Bell",
"G56":"Sindrome do tunel do carpo","G560":"Sindrome do tunel do carpo",
"G57":"Neuropatia ciatica","G570":"Ciatica","G571":"Meralgia parestesica","G572":"Neuropatia femoral",
"G60":"Doenca de Charcot-Marie-Tooth","G610":"Sindrome de Guillain-Barre",
"G70":"Miastenia gravis","G71":"Distrofia muscular","G80":"Paralisia cerebral","G81":"Hemiplegia","G82":"Paraplegia ou tetraplegia",
"H00":"Hordeolo e calazio","H01":"Blefarite",
"H10":"Conjuntivite","H100":"Conjuntivite purulenta","H102":"Conjuntivite aguda","H104":"Conjuntivite cronica","H109":"Conjuntivite nao especificada",
"H16":"Ceratite","H18":"Doenca da cornea","H25":"Catarata senil","H26":"Outras cataratas",
"H33":"Descolamento de retina","H35":"Doenca da retina","H36":"Retinopatia diabetica",
"H40":"Glaucoma","H401":"Glaucoma de angulo aberto","H402":"Glaucoma de angulo fechado","H409":"Glaucoma nao especificado",
"H46":"Neurite optica","H50":"Estrabismo",
"H52":"Erros de refracao","H520":"Hipermetropia","H521":"Miopia","H522":"Astigmatismo","H524":"Presbiopia","H529":"Erro de refracao nao especificado",
"H54":"Cegueira e visao subnormal",
"H60":"Otite externa","H65":"Otite media serosa","H650":"Otite media aguda serosa","H66":"Otite media supurativa","H660":"Otite media supurativa aguda","H661":"Otite media supurativa cronica","H669":"Otite media nao especificada","H70":"Mastoidite",
"H80":"Otosclerose","H810":"Doenca de Meniere","H811":"Vertigem paroxistica benigna","H812":"Neuronite vestibular","H813":"Vertigem periferica","H819":"Vertigem nao especificada",
"H90":"Perda de audicao","H91":"Perda de audicao senil","H92":"Otalgia",
"I00":"Febre reumatica","I05":"Valvopatia mitral reumatica","I06":"Valvopatia aortica reumatica",
"I10":"Hipertensao arterial essencial","I11":"Cardiopatia hipertensiva","I110":"Cardiopatia hipertensiva com insuficiencia cardiaca","I119":"Cardiopatia hipertensiva sem insuficiencia cardiaca","I12":"Nefropatia hipertensiva","I13":"Cardiopatia e nefropatia hipertensiva","I15":"Hipertensao secundaria","I150":"Hipertensao renovascular","I159":"Hipertensao secundaria nao especificada",
"I20":"Angina","I200":"Angina instavel","I209":"Angina nao especificada",
"I21":"Infarto agudo do miocardio","I210":"Infarto anterior transmural","I211":"Infarto inferior transmural","I213":"Infarto transmural nao especificado","I214":"Infarto subendocardico","I219":"IAM nao especificado",
"I25":"Doenca isquemica cronica do coracao","I250":"Aterosclerose coronaria","I251":"Doenca coronariana","I252":"Infarto antigo","I255":"Cardiomiopatia isquemica","I259":"Doenca isquemica cronica nao especificada",
"I26":"Tromboembolia pulmonar","I260":"TEP com cor pulmonale","I269":"TEP sem cor pulmonale",
"I30":"Pericardite aguda","I33":"Endocardite infecciosa","I34":"Insuficiencia mitral","I35":"Estenose ou insuficiencia aortica","I38":"Endocardite valvular nao especificada",
"I40":"Miocardite aguda","I42":"Cardiomiopatia","I420":"Cardiomiopatia dilatada","I421":"Cardiomiopatia hipertrofica obstrutiva","I422":"Cardiomiopatia hipertrofica nao obstrutiva","I426":"Cardiomiopatia alcoolica","I429":"Cardiomiopatia nao especificada",
"I44":"Bloqueio atrioventricular","I45":"Bloqueio de ramo","I47":"Taquicardia paroxistica supraventricular","I48":"Fibrilacao atrial","I490":"Fibrilacao ventricular",
"I50":"Insuficiencia cardiaca","I500":"Insuficiencia cardiaca congestiva","I501":"Insuficiencia ventricular esquerda","I509":"Insuficiencia cardiaca nao especificada",
"I60":"Hemorragia subaracnoide","I61":"Hemorragia intracerebral","I63":"Infarto cerebral","I64":"AVC nao especificado","I65":"Oclusao arteria pre-cerebral","I66":"Oclusao arteria cerebral","I69":"Sequelas de AVC",
"I70":"Aterosclerose","I700":"Aterosclerose de aorta","I702":"Aterosclerose de membros","I709":"Aterosclerose generalizada",
"I71":"Aneurisma de aorta","I72":"Aneurisma arterial","I730":"Fenomeno de Raynaud","I731":"Tromboangeite obliterante","I739":"Doenca vascular periferica nao especificada",
"I74":"Embolia arterial","I80":"Tromboflebite","I82":"Trombose venosa profunda","I83":"Varizes de membros inferiores","I84":"Hemorroidas","I85":"Varizes esofagianas",
"J00":"Resfriado comum - nasofaringite aguda",
"J01":"Sinusite aguda","J010":"Sinusite maxilar aguda","J011":"Sinusite frontal aguda","J012":"Sinusite etmoidal aguda","J019":"Sinusite aguda nao especificada",
"J02":"Faringite aguda","J020":"Faringite estreptococica","J029":"Faringite aguda nao especificada",
"J03":"Amigdalite aguda","J030":"Amigdalite estreptococica","J039":"Amigdalite aguda nao especificada",
"J04":"Laringite aguda","J05":"Crupe","J06":"IVAS - Infeccao vias aereas superiores",
"J09":"Gripe aviaria","J10":"Influenza","J11":"Gripe nao especificada",
"J12":"Pneumonia viral","J13":"Pneumonia pneumococica","J14":"Pneumonia por H. influenzae","J15":"Pneumonia bacteriana","J150":"Pneumonia por Klebsiella","J151":"Pneumonia por Pseudomonas","J152":"Pneumonia estafilococica","J157":"Pneumonia por Mycoplasma","J159":"Pneumonia bacteriana nao especificada","J18":"Pneumonia nao especificada",
"J20":"Bronquite aguda","J209":"Bronquite aguda nao especificada","J21":"Bronquiolite aguda",
"J30":"Rinite alergica","J300":"Rinite vasomotora","J301":"Rinite alergica por polens","J303":"Rinite alergica perene","J309":"Rinite alergica nao especificada",
"J32":"Sinusite cronica","J320":"Sinusite maxilar cronica","J329":"Sinusite cronica nao especificada","J33":"Polipo nasal",
"J35":"Amigdalite cronica e adenoide","J36":"Abscesso periamigdaliano","J37":"Laringite cronica","J38":"Doenca das cordas vocais",
"J40":"Bronquite nao especificada","J41":"Bronquite cronica","J43":"Enfisema","J439":"Enfisema nao especificado",
"J44":"DPOC","J440":"DPOC com infeccao","J441":"DPOC com exacerbacao","J449":"DPOC nao especificada",
"J45":"Asma","J450":"Asma alergica","J451":"Asma nao alergica","J459":"Asma nao especificada","J46":"Estado de mal asmatico",
"J47":"Bronquiectasia","J62":"Silicose","J67":"Pneumonite de hipersensibilidade",
"J80":"SARA - Sindrome de angustia respiratoria aguda","J81":"Edema pulmonar agudo",
"J84":"Doenca pulmonar intersticial","J85":"Abscesso pulmonar","J90":"Derrame pleural","J93":"Pneumotorax","J96":"Insuficiencia respiratoria","J960":"Insuficiencia respiratoria aguda","J961":"Insuficiencia respiratoria cronica",
"K01":"Dente impactado","K02":"Carie dental","K03":"Desgaste dental","K04":"Abscesso dentario","K05":"Doenca periodontal","K08":"Perda dental",
"K20":"Esofagite","K21":"Refluxo gastroesofagico - DRGE","K210":"DRGE com esofagite","K219":"DRGE sem esofagite",
"K25":"Ulcera gastrica","K250":"Ulcera gastrica aguda hemorragica","K253":"Ulcera gastrica aguda","K259":"Ulcera gastrica nao especificada","K26":"Ulcera duodenal","K27":"Ulcera peptica",
"K29":"Gastrite","K290":"Gastrite hemorragica","K291":"Gastrite aguda","K292":"Gastrite alcoolica","K293":"Gastrite cronica superficial","K294":"Gastrite atrofica","K297":"Gastrite nao especificada",
"K30":"Dispepsia funcional",
"K35":"Apendicite aguda com peritonite","K37":"Apendicite nao especificada","K38":"Outras doencas do apendice",
"K40":"Hernia inguinal","K40":"Hernia inguinal bilateral","K409":"Hernia inguinal nao especificada","K41":"Hernia femoral","K42":"Hernia umbilical","K43":"Hernia incisional","K44":"Hernia de hiato",
"K50":"Doenca de Crohn","K500":"Doenca de Crohn intestino delgado","K501":"Doenca de Crohn intestino grosso","K509":"Doenca de Crohn nao especificada",
"K51":"Retocolite ulcerativa","K519":"Retocolite ulcerativa nao especificada","K52":"Colite nao infecciosa",
"K57":"Diverticulose","K58":"Sindrome do intestino irritavel","K580":"SII com diarreia","K589":"SII sem diarreia","K59":"Constipacao",
"K61":"Abscesso retal","K64":"Hemorroidas","K64":"Hemorroidas e trombose hemorroidaria",
"K70":"Hepatopatia alcoolica","K72":"Insuficiencia hepatica","K73":"Hepatite cronica","K74":"Cirrose hepatica","K740":"Fibrose hepatica","K746":"Cirrose nao especificada",
"K76":"Doenca hepatica cronica","K760":"Esteatose hepatica","K766":"Hipertensao portal","K769":"Doenca hepatica nao especificada",
"K80":"Colelitíase","K800":"Colecistite aguda litiasica","K802":"Colelitíase sem colecistite","K803":"Coledocolitíase com colangite","K81":"Colecistite","K810":"Colecistite aguda","K811":"Colecistite cronica","K819":"Colecistite nao especificada",
"K85":"Pancreatite aguda","K86":"Pancreatite cronica","K860":"Pancreatite cronica alcoolica","K868":"Outras doencas do pancreas",
"L01":"Impetigo","L02":"Abscesso e furunculos","L03":"Celulite","L04":"Linfadenite aguda","L05":"Cisto pilonidal",
"L20":"Dermatite atopica - eczema","L21":"Dermatite seborreica","L23":"Dermatite alergica de contato","L24":"Dermatite irritativa","L25":"Dermatite de contato nao especificada","L29":"Prurido",
"L40":"Psoriase","L400":"Psoriase vulgar","L405":"Artropatia psoriatica","L409":"Psoriase nao especificada",
"L50":"Urticaria","L51":"Eritema multiforme","L52":"Eritema nodoso","L55":"Queimadura solar",
"L63":"Alopecia areata","L64":"Alopecia androgenetica","L65":"Queda de cabelo","L66":"Alopecia cicatricial",
"L70":"Acne","L700":"Acne vulgar","L709":"Acne nao especificada","L71":"Rosácea","L80":"Vitiligo","L81":"Hiperpigmentacao","L82":"Ceratose seborreica","L83":"Acantose nigricante",
"L89":"Ulcera de pressao","L97":"Ulcera de perna","L98":"Outras doencas da pele",
"M00":"Artrite séptica","M01":"Artrite infecciosa",
"M05":"Artrite reumatoide soropositiva","M06":"Artrite reumatoide soronegativa","M07":"Artropatia psoriatica","M08":"Artrite juvenil","M10":"Gota","M100":"Gota idiopatica","M109":"Gota nao especificada",
"M15":"Poliarttrose","M16":"Artrose de quadril","M160":"Coxartrose primaria bilateral","M169":"Coxartrose nao especificada","M17":"Artrose de joelho","M170":"Gonartrose primaria bilateral","M171":"Gonartrose primaria unilateral","M179":"Gonartrose nao especificada","M19":"Artrose nao especificada",
"M20":"Joanete - Hallux valgus","M23":"Lesao interna do joelho","M24":"Lesao articular especifica","M25":"Dor articular nao especificada",
"M32":"Lupus eritematoso sistemico","M329":"LES nao especificado","M33":"Dermatomiosite","M34":"Esclerodermia","M35":"Sindrome de Sjogren","M36":"Artropatia em doencas sistemicas",
"M40":"Cifose","M41":"Escoliose","M45":"Espondilite anquilosante","M47":"Espondilose","M48":"Estenose de canal vertebral",
"M50":"Hernia de disco cervical","M51":"Hernia de disco lombar","M510":"Hernia de disco lombossacra com mielopatia","M511":"Hernia de disco lombossacra com radiculopatia","M519":"Hernia de disco nao especificada",
"M54":"Dorsalgia","M540":"Cervicalgia","M541":"Radiculopatia","M542":"Cervicalgia","M543":"Ciatica","M544":"Lombociatalgia","M545":"Lombalgia","M549":"Dor nas costas nao especificada",
"M60":"Miosite","M65":"Sinovite e tenossinovite","M67":"Tendinite",
"M75":"Lesao de ombro","M750":"Ombro congelado - capsulite adesiva","M751":"Sindrome do manguito rotador","M754":"Sindrome do impacto subacromial","M755":"Bursite subacromial","M759":"Lesao de ombro nao especificada",
"M77":"Epicondilite","M771":"Epicondilite lateral - cotovelo de tenista","M772":"Epicondilite medial - cotovelo de golfista",
"M79":"Fibromialgia e outros transtornos","M797":"Fibromialgia",
"M80":"Osteoporose com fratura","M81":"Osteoporose sem fratura","M810":"Osteoporose pos-menopausica","M819":"Osteoporose nao especificada","M83":"Osteomalacia","M86":"Osteomielite","M87":"Osteonecrose","M88":"Doenca de Paget",
"N00":"Glomerulonefrite aguda","N03":"Glomerulonefrite cronica","N04":"Sindrome nefrotica","N17":"Lesao renal aguda","N170":"LRA com necrose tubular","N179":"LRA nao especificada","N18":"Doenca renal cronica","N180":"DRC estadio final","N181":"DRC estadio 1","N182":"DRC estadio 2","N183":"DRC estadio 3","N184":"DRC estadio 4","N185":"DRC estadio 5","N189":"DRC nao especificada","N19":"Insuficiencia renal nao especificada",
"N20":"Calculose renal","N200":"Calculo do rim","N201":"Calculo do ureter","N209":"Calculose nao especificada","N23":"Colica renal",
"N30":"Cistite","N300":"Cistite aguda","N309":"Cistite nao especificada","N34":"Uretrite","N39":"Infeccao urinaria","N390":"ITU - Infeccao do trato urinario","N393":"Incontinencia urinaria de esforco","N394":"Incontinencia urinaria de urgência","N399":"Transtorno urinario nao especificado",
"N40":"Hiperplasia prostatica benigna","N41":"Prostatite","N410":"Prostatite aguda","N411":"Prostatite cronica","N419":"Prostatite nao especificada","N42":"Doenca da prostata","N45":"Orquite e epididimite","N46":"Infertilidade masculina","N48":"Disfuncao eretil",
"N60":"Displasia mamaria benigna","N61":"Mastite","N63":"Nodulo mamario","N64":"Mastodinia",
"N70":"Doenca inflamatoria pelvica - DIP","N71":"Endometrite","N72":"Cervicite","N73":"DIP nao especificada","N76":"Vulvovaginite",
"N80":"Endometriose","N800":"Endometriose uterina","N801":"Endometriose ovariana","N809":"Endometriose nao especificada",
"N81":"Prolapso uterino","N83":"Cisto de ovario","N84":"Polipo uterino","N85":"Hiperplasia de endometrio","N87":"Displasia do colo do utero - NIC","N88":"Ectopia cervical","N90":"Cisto de Bartholin","N91":"Amenorreia","N92":"Menorragia","N93":"Sangramento uterino anormal","N94":"Dismenorreia","N940":"Dismenorreia","N941":"Dispareunia","N943":"Sindrome pre-menstrual - SPM","N949":"Afeccao ginecologica nao especificada",
"N95":"Sindrome do climatério","N950":"Sangramento pos-menopausico","N951":"Sintomas da menopausa","N952":"Vaginite atrofica","N959":"Menopausa nao especificada",
"N97":"Infertilidade feminina",
"O00":"Gravidez ectopica","O001":"Gravidez tubaria","O009":"Gravidez ectopica nao especificada","O01":"Mola hidatiforme","O03":"Abortamento espontaneo","O04":"Aborto induzido",
"O10":"Hipertensao cronica na gravidez","O13":"Hipertensao gestacional","O14":"Pre-eclampsia","O140":"Pre-eclampsia moderada","O141":"Pre-eclampsia grave","O149":"Pre-eclampsia nao especificada","O15":"Eclampsia",
"O20":"Sangramento no primeiro trimestre","O21":"Hiperemese gravidica","O22":"Trombose venosa na gravidez","O23":"ITU na gravidez","O24":"Diabetes gestacional",
"O30":"Gravidez multipla","O42":"Ruptura prematura das membranas","O44":"Placenta previa","O45":"Descolamento de placenta","O47":"Ameaca de parto prematuro","O60":"Trabalho de parto prematuro",
"O80":"Parto normal","O82":"Cesarea","O85":"Sepse puerperal","O86":"Infeccao puerperal","O90":"Complicacoes puerperais","O91":"Mastite puerperal",
"Q00":"Anencefalia","Q02":"Microcefalia","Q03":"Hidrocefalia congenita","Q05":"Espinha bifida","Q21":"Comunicacao interventricular - CIV","Q25":"Malformacao de grandes arterias","Q35":"Fissura palatina","Q36":"Fenda labial","Q37":"Fenda labiopalatina",
"Q54":"Hipospadia","Q65":"Displasia de quadril","Q66":"Pe torto congenito",
"Q90":"Sindrome de Down","Q91":"Sindrome de Edwards","Q96":"Sindrome de Turner",
"R00":"Palpitacoes","R01":"Sopro cardiaco","R03":"Hipertensao sem diagnostico","R04":"Epistaxe - sangramento nasal","R05":"Tosse","R06":"Dispneia","R07":"Dor toracica","R09":"Outros sintomas cardiorrespiratorios",
"R10":"Dor abdominal","R100":"Abdome agudo","R101":"Dor epigastrica","R104":"Dor abdominal difusa","R11":"Nausea e vomito","R12":"Pirose","R13":"Disfagia","R15":"Incontinencia fecal","R16":"Hepatomegalia","R17":"Ictericia","R18":"Ascite",
"R20":"Dormencia e formigamento","R21":"Eruppcao cutanea","R22":"Massa ou nodulo","R25":"Tremor","R26":"Alteracao da marcha",
"R30":"Disuria","R31":"Hematuria","R32":"Incontinencia urinaria","R33":"Retencao urinaria","R35":"Poliuria","R39":"Sintomas urinarios nao especificados",
"R40":"Coma","R41":"Confusao mental","R42":"Tontura e vertigem","R43":"Anosmia","R44":"Alucinacao","R47":"Afasia","R48":"Dislexia",
"R50":"Febre sem causa aparente","R51":"Cefaleia","R52":"Dor cronica","R53":"Fadiga e astenia","R55":"Sincope","R56":"Convulsao","R57":"Choque","R58":"Hemorragia nao especificada","R59":"Linfadenopatia","R60":"Edema","R62":"Atraso no desenvolvimento","R63":"Anorexia","R64":"Caquexia",
"R70":"VHS elevada","R73":"Hiperglicemia","R74":"Enzimas hepaticas alteradas","R75":"Teste positivo para HIV","R79":"Exame bioquimico alterado","R80":"Proteinuria","R81":"Glicosuria","R82":"Exame de urina alterado",
"R90":"TC de cranio alterada","R91":"Imagem pulmonar alterada","R93":"Exame de imagem alterado","R94":"Exame funcional alterado",
"S02":"Fratura de cranio","S06":"Traumatismo cranioencefalico","S09":"Traumatismo de cabeca",
"S12":"Fratura de coluna cervical","S22":"Fratura de costela","S32":"Fratura de coluna lombar",
"S42":"Fratura de ombro","S52":"Fratura de antebraco","S62":"Fratura de punho ou mao","S72":"Fratura de femur","S82":"Fratura de perna","S92":"Fratura de pe",
"T14":"Traumatismo nao especificado","T30":"Queimadura","T39":"Intoxicacao por analgesicos","T40":"Intoxicacao por opioides","T43":"Intoxicacao por psicofarmacos","T51":"Intoxicacao por alcool","T57":"Intoxicacao por metais","T58":"Intoxicacao por CO","T65":"Intoxicacao nao especificada",
"T74":"Maus tratos","T78":"Anafilaxia","T79":"Complicacao de traumatismo",
"T80":"Reacao a transfusao","T81":"Complicacao cirurgica","T86":"Rejeicao de transplante","T88":"Choque anafilatico",
"Z00":"Consulta de rotina","Z001":"Check-up infantil","Z008":"Check-up adulto","Z009":"Exame nao especificado",
"Z01":"Exame preventivo","Z02":"Exame admissional","Z08":"Seguimento pos-cancer","Z09":"Seguimento pos-tratamento","Z10":"Exame de saude ocupacional","Z11":"Rastreio de doencas infecciosas","Z12":"Rastreio de cancer","Z13":"Rastreio de outras doencas",
"Z20":"Contato com doenca contagiosa","Z21":"Portador assintomatico de HIV","Z22":"Portador de doenca infecciosa",
"Z23":"Vacinacao contra doencas bacterianas","Z24":"Vacinacao contra doencas virais","Z26":"Vacinacao","Z28":"Vacinacao nao realizada",
"Z30":"Anticoncepção","Z31":"Planejamento familiar","Z32":"Teste de gravidez","Z33":"Gravidez confirmada","Z34":"Pre-natal de baixo risco","Z35":"Pre-natal de alto risco",
"Z51":"Quimioterapia","Z512":"Radioterapia","Z515":"Cuidados paliativos",
"Z54":"Convalescença","Z72":"Tabagismo","Z720":"Tabagismo","Z721":"Alcoolismo","Z722":"Uso de drogas","Z73":"Burnout","Z74":"Dependencia de cuidadores","Z75":"Falta de acesso a servico de saude",
"Z80":"Historia familiar de cancer","Z81":"Historia familiar de doenca mental","Z82":"Historia familiar de doencas cronicas","Z85":"Cancer previo","Z86":"Historia pessoal de outras doencas","Z87":"Historia pessoal","Z88":"Alergia a medicamentos","Z89":"Amputacao","Z91":"Historia de riscos","Z93":"Ostomia","Z94":"Transplante de orgaos","Z95":"Implante cardiovascular","Z96":"Implante funcional","Z98":"Estado pos-cirurgico","Z99":"Dependencia de dispositivos",
// EXPANSÃO — Cardiologia detalhada
"I200":"Angina instavel","I201":"Angina variante de Prinzmetal","I208":"Outras anginas especificadas",
"I210":"IAM anterior transmural","I211":"IAM inferior transmural","I212":"IAM lateral transmural","I213":"IAM transmural nao especificado","I214":"IAM subendocardico","I219":"IAM nao especificado",
"I220":"IAM recorrente anterior","I221":"IAM recorrente inferior","I228":"IAM recorrente de outros locais","I229":"IAM recorrente nao especificado",
"I230":"Hemopericardio pos IAM","I231":"Defeito septal atrial pos IAM","I232":"Defeito septal ventricular pos IAM","I233":"Ruptura parede cardiaca sem hemopericardio pos IAM","I234":"Ruptura corda tendinea pos IAM","I235":"Ruptura musculo papilar pos IAM","I236":"Trombose atrial auricular e ventricular pos IAM",
"I441":"Bloqueio atrioventricular de segundo grau","I442":"Bloqueio atrioventricular total","I450":"Bloqueio fascicular anterior esquerdo","I451":"Outros bloqueios de ramo esquerdo","I452":"Bloqueio bifascicular","I453":"Bloqueio trifascicular","I454":"Bloqueio de ramo direito","I455":"Outro bloqueio fascicular","I456":"Sindrome de pre-excitacao","I459":"Disturbio de conducao nao especificado",
"I470":"Re-entrada ventricular","I471":"Taquicardia supraventricular","I472":"Taquicardia ventricular","I479":"Taquicardia paroxistica nao especificada",
"I480":"Fibrilacao atrial paroxistica","I481":"Fibrilacao atrial persistente","I482":"Fibrilacao atrial cronica","I483":"Flutter atrial tipico","I484":"Flutter atrial atipico","I489":"Fibrilacao e flutter atrial nao especificados",
"I490":"Fibrilacao e flutter ventriculares","I491":"Despolarizacao atrial prematura","I492":"Despolarizacao juncional prematura","I493":"Despolarizacao ventricular prematura","I494":"Outras despolarizacoes prematuras","I495":"Sindrome de seno doente","I498":"Outras arritmias cardiacas especificadas","I499":"Arritmia cardiaca nao especificada",
"I500":"ICC - Insuficiencia cardiaca congestiva","I501":"Insuficiencia ventricular esquerda aguda","I509":"Insuficiencia cardiaca nao especificada",
"I510":"Defeito septal adquirido","I511":"Ruptura de corda tendinea","I512":"Ruptura de musculo papilar","I513":"Trombose intracardiaca","I514":"Miocardite nao especificada","I515":"Degeneracao miocardica","I516":"Doenca cardiovascular nao especificada","I517":"Cardiomegalia","I518":"Outras doencas mal definidas do coracao","I519":"Doenca cardiaca nao especificada",
// Valvopatias detalhadas
"I340":"Insuficiencia mitral","I341":"Prolapso da valva mitral","I342":"Estenose mitral nao reumatica","I348":"Outros transtornos nao reumaticos da valva mitral","I349":"Transtorno nao reumatico da valva mitral nao especificado",
"I350":"Estenose aortica","I351":"Insuficiencia aortica","I352":"Estenose com insuficiencia aortica","I358":"Outros transtornos da valva aortica","I359":"Transtorno da valva aortica nao especificado",
// Doenca arterial periferica
"I700":"Aterosclerose de aorta","I701":"Aterosclerose da arteria renal","I702":"Aterosclerose das arterias dos membros","I7020":"Aterosclerose de membros sem gangrena","I7021":"Aterosclerose de membros com gangrena","I708":"Aterosclerose de outras arterias","I709":"Aterosclerose generalizada",
"I731":"Tromboangeite obliterante - Buerger","I738":"Outras doencas vasculares perifericas","I739":"DAP - Doenca arterial periferica nao especificada",
// EXPANSÃO — Neurologia detalhada
"G300":"Alzheimer precoce antes 65 anos","G301":"Alzheimer tardio apos 65 anos","G309":"Alzheimer nao especificado",
"G200":"Doenca de Parkinson idiopatica","G210":"Parkinsonismo por drogas","G212":"Parkinsonismo secundario por outros agentes externos","G213":"Parkinsonismo pos-encefalite","G219":"Parkinsonismo secundario nao especificado",
"G310":"Atrofia cerebral focal","G311":"Degeneracao senil do cerebro","G312":"Degeneracao do sistema nervoso por alcool","G318":"Outras degeneracoes do sistema nervoso especificadas","G319":"Degeneracao do sistema nervoso nao especificada",
"G350":"Esclerose multipla surto-remissao","G351":"Esclerose multipla progressiva primaria","G352":"Esclerose multipla progressiva secundaria","G359":"Esclerose multipla nao especificada",
"G400":"Epilepsia focal idiopatica","G401":"Epilepsia focal sintomatica com convulsoes simples","G402":"Epilepsia focal sintomatica com convulsoes complexas","G403":"Epilepsia generalizada idiopatica","G404":"Outras epilepsias generalizadas","G405":"Sindromes epilepticas especiais","G406":"Convulsoes de grande mal","G407":"Convulsoes de pequeno mal","G408":"Outras epilepsias","G409":"Epilepsia nao especificada",
"G430":"Enxaqueca sem aura - enxaqueca comum","G431":"Enxaqueca com aura - enxaqueca classica","G432":"Estado de mal enxaquecoso","G433":"Enxaqueca complicada","G434":"Enxaqueca retiniana","G435":"Enxaqueca periodica na infancia","G436":"Enxaqueca com aura prolongada","G438":"Outras enxaquecas","G439":"Enxaqueca nao especificada",
"G440":"Cefaleia em salvas episodica","G441":"Hemicrania paroxistica","G442":"Cefaleia tensional episodica","G443":"Cefaleia tensional cronica","G444":"Cefaleia por uso excessivo de medicamento","G448":"Outras cefaleias especificadas","G449":"Cefaleia nao especificada",
"G450":"Sindrome vertebrobasilar - insuficiencia vertebrobasilar","G451":"Sindrome da arteria carotida","G452":"Ataques isquemicos transitorios multiplos","G453":"Amaurose fugaz","G454":"Amnesia global transitoria","G459":"AIT - Ataque isquemico transitorio nao especificado",
"G470":"Insonia primaria","G471":"Hipersonia primaria","G472":"Transtorno do ritmo circadiano","G473":"Apneia obstrutiva do sono","G474":"Narcolepsia","G475":"Parassonias","G478":"Outros transtornos do sono","G479":"Transtorno do sono nao especificado",
"G500":"Nevralgia do trigemeo","G501":"Espasmo do nervo facial","G508":"Outros transtornos do nervo trigemeo","G509":"Transtorno do nervo trigemeo nao especificado",
"G560":"Sindrome do tunel do carpo","G561":"Lesao do nervo mediano","G562":"Lesao do nervo ulnar - cubital","G563":"Lesao do nervo radial","G568":"Outras mononeuropatias do membro superior","G569":"Mononeuropatia do membro superior nao especificada",
"G610":"Sindrome de Guillain-Barre","G611":"Neuropatia sensoriomotora hereditaria","G618":"Outras polineuropatias inflamatorias","G619":"Polineuropatia inflamatoria nao especificada",
"G620":"Polineuropatia induzida por drogas","G621":"Polineuropatia alcoolica","G622":"Polineuropatia devida a outros agentes toxicos","G628":"Outras polineuropatias especificadas","G629":"Polineuropatia nao especificada",
"G700":"Miastenia gravis","G701":"Miastenia gravis toxica","G708":"Outros transtornos da juncao neuromuscular","G709":"Transtorno da juncao neuromuscular nao especificado",
"G710":"Distrofia muscular de Duchenne","G711":"Distrofia muscular de Becker","G712":"Miopatia congenita","G713":"Miopatia mitocondrial","G718":"Outras distrofias musculares","G719":"Distrofia muscular nao especificada",
"G800":"Paralisia cerebral espastica","G801":"Diplegia espasstica","G802":"Hemiplegia infantil","G803":"Paralisia cerebral disquinetica","G804":"Ataxia cerebral","G808":"Outras paralisis cerebrais","G809":"Paralisia cerebral nao especificada",
// EXPANSÃO — Endocrinologia detalhada
"E050":"Doenca de Graves - bócio difuso toxico","E051":"Nodulo toxico uninodular","E052":"Bócio multinodular toxico","E053":"Tecido tiroidiano ectopico toxico","E054":"Tireotoxicose facticia","E055":"Crise tireotoxica - tempestade tiroidiana","E058":"Outras tireotoxicoses","E059":"Tireotoxicose nao especificada",
"E060":"Tiroidite supurativa aguda","E061":"Tiroidite subaguda de De Quervain","E062":"Tiroidite cronica com tireotoxicose transitoria","E063":"Tiroidite de Hashimoto","E064":"Tiroidite induzida por drogas","E065":"Tiroidite de Riedel","E069":"Tiroidite nao especificada",
"E100":"DM tipo 1 com coma hiperosmolar","E101":"DM tipo 1 com cetoacidose sem coma","E102":"DM tipo 1 com nefropatia","E103":"DM tipo 1 com retinopatia","E1030":"DM tipo 1 com retinopatia nao especificada","E1031":"DM tipo 1 com retinopatia de fundo","E1032":"DM tipo 1 com retinopatia proliferativa","E104":"DM tipo 1 com neuropatia","E105":"DM tipo 1 com angiopatia periferica","E106":"DM tipo 1 com outras complicacoes","E107":"DM tipo 1 com multiplas complicacoes","E109":"DM tipo 1 sem complicacoes",
"E110":"DM tipo 2 com coma hiperosmolar","E111":"DM tipo 2 com cetoacidose","E112":"DM tipo 2 com nefropatia - nefropatia diabetica","E113":"DM tipo 2 com retinopatia","E1130":"DM tipo 2 com retinopatia nao especificada","E1131":"DM tipo 2 com retinopatia de fundo","E1132":"DM tipo 2 com retinopatia proliferativa","E114":"DM tipo 2 com neuropatia","E115":"DM tipo 2 com angiopatia periferica","E116":"DM tipo 2 com outras complicacoes","E117":"DM tipo 2 com multiplas complicacoes","E119":"DM tipo 2 sem complicacoes",
"E240":"Sindrome de Cushing dependente de ACTH hipofisaria","E241":"Sindrome de Nelson","E242":"Sindrome de Cushing por drogas","E243":"Sindrome do ACTH ectopico","E244":"Sindrome de pseudo-Cushing por alcool","E249":"Sindrome de Cushing nao especificada",
"E260":"Hiperaldosteronismo primario - Sindrome de Conn","E261":"Hiperaldosteronismo secundario","E268":"Outros hiperaldosteronismos","E269":"Hiperaldosteronismo nao especificado",
"E270":"Hiperatividade cortical suprarrenal","E271":"Insuficiencia suprarrenal primaria - Addison","E272":"Crise addisoniana","E273":"Insuficiencia corticosuprarrenal por drogas","E274":"Outras insuficiencias corticosuprarrenais","E275":"Hiperfuncao adrenomedular","E276":"Hipoatividade cortical suprarrenal","E278":"Outros transtornos suprarrenais","E279":"Transtorno suprarrenal nao especificado",
"E280":"Excesso de estrogenios","E281":"Excesso de androgenios","E282":"Sindrome dos ovarios policisticos - SOP","E283":"Insuficiencia ovariana primaria","E288":"Outras disfuncoes ovarianas","E289":"Disfuncao ovariana nao especificada",
"E780":"Hipercolesterolemia pura - LDL elevado","E781":"Hipertrigliceridemia pura","E782":"Hiperlipidemia mista - LDL e triglicerides elevados","E783":"Hiperquilomicronemia familiar","E784":"Outras hiperlipidemias","E785":"Hiperlipidemia nao especificada","E786":"Deficiencia de HDL","E787":"Hiperlipoproteinemia","E788":"Dislipidemia aterogênica - sindrome metabolica","E789":"Dislipidemia nao especificada",
// EXPANSÃO — Reumatologia
"M050":"Sindrome de Felty","M051":"Doenca pulmonar reumatoide","M052":"Vasculite reumatoide","M053":"Artrite reumatoide com envolvimento de outros orgaos","M058":"Outras artrites reumatoides soropositivas","M059":"Artrite reumatoide soropositiva nao especificada",
"M060":"Artrite reumatoide soronegativa","M061":"Doenca de Still do adulto","M062":"Bursite reumatoide","M063":"Nodulo reumatoide","M064":"Poliartropatia inflamatoria","M068":"Outras artrites reumatoides especificadas","M069":"Artrite reumatoide nao especificada",
"M320":"LES induzido por drogas","M321":"LES com comprometimento renal - nefrite lupica","M322":"LES com comprometimento nervoso","M323":"LES com comprometimento cardiopulmonar","M324":"LES com comprometimento cutaneo","M325":"LES com comprometimento hematologico","M329":"LES nao especificado",
"M340":"Esclerose sistemica progressiva - CREST","M341":"Sindrome CR(E)ST","M342":"Esclerose sistemica induzida por drogas","M348":"Outras formas de esclerose sistemica","M349":"Esclerose sistemica nao especificada",
"M350":"Sindrome de Sjogren","M351":"Outras sindromes de superposicao","M352":"Doenca de Behcet","M353":"Polimialgia reumatica","M354":"Fascite difusa","M355":"Fibrosclerose multifocal","M356":"Paniculite recidivante de Weber-Christian","M358":"Outras afeccoes sistemicas","M359":"Afeccao sistemica nao especificada",
"M450":"Espondilite anquilosante da regiao lombossacral","M451":"Espondilite anquilosante da regiao lombossacral","M452":"Espondilite anquilosante da regiao cervicotorcica","M453":"Espondilite anquilosante da regiao toracica","M454":"Espondilite anquilosante da regiao toracolombar","M455":"Espondilite anquilosante da regiao lombar","M456":"Espondilite anquilosante da regiao lombossacral","M457":"Espondilite anquilosante da regiao sacral","M458":"Espondilite anquilosante da coluna toda","M459":"Espondilite anquilosante de localizacao nao especificada",
// EXPANSÃO — Pneumologia detalhada
"J440":"DPOC com infeccao respiratoria do trato inferior","J441":"DPOC com exacerbacao aguda","J448":"Outras formas de DPOC","J449":"DPOC nao especificada",
"J450":"Asma alergica predominante","J451":"Asma nao alergica","J452":"Asma mista","J458":"Asma moderada persistente","J459":"Asma nao especificada - asma bronquica",
"J700":"Pneumonite aguda por radiacao","J701":"Fibrose pulmonar cronica por radiacao","J702":"Transtornos respiratorios agudos por agentes quimicos","J703":"Transtornos respiratorios cronicos por agentes quimicos","J704":"Transtornos respiratorios por outros agentes","J708":"Afeccoes respiratorias por outros agentes","J709":"Afeccao respiratoria por agente externo nao especificado",
"J840":"Condicoes com fibrose alveolar","J841":"Outras doencas pulmonares intersticiais com fibrose","J848":"Outras doencas pulmonares intersticiais especificadas","J849":"Doenca pulmonar intersticial nao especificada",
"J960":"Insuficiencia respiratoria aguda","J961":"Insuficiencia respiratoria cronica","J969":"Insuficiencia respiratoria nao especificada",
// EXPANSÃO — Gastroenterologia detalhada
"K500":"Doenca de Crohn do intestino delgado - ileite","K501":"Doenca de Crohn do colon - colite de Crohn","K502":"Doenca de Crohn do intestino delgado e grosso","K508":"Outras formas de Crohn","K509":"Doenca de Crohn nao especificada",
"K510":"Enterocolite ulcerativa","K511":"Ileocolite ulcerativa","K512":"Proctite ulcerativa","K513":"Retossigmoidite ulcerativa","K514":"Pseudopolipose do colon","K515":"Proctocolite mucosa","K518":"Outras colites ulcerativas","K519":"Colite ulcerativa nao especificada",
"K700":"Fígado gorduroso alcoolico - esteatose alcoolica","K701":"Hepatite alcoolica","K702":"Fibrose e esclerose hepatica alcoolica","K703":"Cirrose hepatica alcoolica","K704":"Insuficiencia hepatica alcoolica","K709":"Doenca alcoolica do figado nao especificada",
"K740":"Fibrose hepatica","K741":"Esclerose hepatica","K742":"Fibrose e esclerose hepaticas","K743":"Cirrose biliar primaria - colangite biliar primaria","K744":"Cirrose biliar secundaria","K745":"Cirrose biliar nao especificada","K746":"Cirrose hepatica - cirrose hepatica nao especificada",
"K760":"DHGNA - Doenca hepatica gordurosa nao alcoolica - esteatose hepatica","K761":"Congestao hepatica","K762":"Hemorragia central do lobulo hepatico","K763":"Infarto hepatico","K764":"Peliose hepatica","K765":"Doenca veno-oclusiva","K766":"Hipertensao portal","K767":"Sindrome hepatorrenal","K768":"Outras doencas especificadas do figado","K769":"Doenca hepatica nao especificada",
"K860":"Pancreatite cronica de etiologia alcoolica","K861":"Outras pancreatites cronicas","K862":"Cisto do pancreas","K863":"Pseudocisto do pancreas","K864":"Insuficiencia exocrina do pancreas","K868":"Outras doencas especificadas do pancreas","K869":"Doenca do pancreas nao especificada",
// EXPANSÃO — Nefrologia detalhada
"N180":"DRC estadio 5 com dialise - DRC terminal","N181":"DRC estadio 1 - funcao renal preservada","N182":"DRC estadio 2 - reducao leve da funcao renal","N183":"DRC estadio 3 - reducao moderada da funcao renal","N184":"DRC estadio 4 - reducao grave da funcao renal","N185":"DRC estadio 5 sem dialise","N188":"Outras doencas renais cronicas","N189":"DRC nao especificada",
"N170":"LRA - Lesao renal aguda com necrose tubular","N171":"LRA com necrose cortical aguda","N172":"LRA com necrose medular","N178":"Outras LRA especificadas","N179":"LRA nao especificada",
"N040":"Sindrome nefrotica com lesoes minimas","N041":"Sindrome nefrotica com alteracoes glomerulares focais","N042":"Sindrome nefrotica com glomerulonefrite membranosa","N043":"Sindrome nefrotica com GNMP tipo 1","N044":"Sindrome nefrotica com GNMP tipo 2","N045":"Sindrome nefrotica com GN mesangial difusa","N046":"Sindrome nefrotica com GN membranoproliferativa","N048":"Sindrome nefrotica com outras alteracoes","N049":"Sindrome nefrotica nao especificada",
// EXPANSÃO — Oncologia/Hematologia
"C900":"Mieloma multiplo","C901":"Leucemia de plasmocitos","C902":"Plasmocitoma extramedular","C903":"Mieloma solitario",
"C910":"LLA - Leucemia linfoide aguda","C911":"LLC - Leucemia linfoide cronica","C912":"Leucemia prolinfocitica de celulas B","C913":"Leucemia de celulas cabeludas - tricoleucemia","C914":"Leucemia prolinfocitica de celulas T","C915":"LLA adulto - leucemia linfocitica aguda","C919":"Leucemia linfoide nao especificada",
"C920":"LMA - Leucemia mieloide aguda","C921":"LMC - Leucemia mieloide cronica","C922":"Leucemia mieloide subaguda","C923":"Sarcoma mieloide","C924":"Leucemia promielocitica aguda - LPA M3","C925":"Leucemia mielomonocitica aguda","C926":"LMA com anomalia 11q23","C927":"LMA com displasia multilinear","C928":"Outras LMA especificadas","C929":"Leucemia mieloide nao especificada",
"C810":"Linfoma de Hodgkin com predominancia linfocitica","C811":"Esclerose nodular de Hodgkin","C812":"Celularidade mista de Hodgkin","C813":"Deplecao linfocitica de Hodgkin","C814":"Linfoma de Hodgkin rico em linfocitos","C819":"Linfoma de Hodgkin nao especificado",
"C830":"Linfoma linfocitico de celulas pequenas - LLC/SLL","C831":"Linfoma de celulas do manto","C832":"Linfoma difuso de celulas pequenas com fendas","C833":"Linfoma de grandes celulas B difuso - LBGD","C835":"Linfoma linfoblastico","C836":"Linfoma de Burkitt","C838":"Outros linfomas B difusos","C839":"Linfoma nao-Hodgkin difuso nao especificado",
"D460":"Anemia refrataria sem sideroblastos","D461":"Anemia refrataria com sideroblastos","D462":"Anemia refrataria com excesso de blastos - AREB","D463":"AREB em transformacao","D464":"Anemia refrataria nao especificada","D467":"Sindrome mielodisplasica com del 5q","D469":"Sindrome mielodisplasica nao especificada",
// EXPANSÃO — Dermatologia
"L400":"Psoriase vulgar - psoriase em placas","L401":"Psoriase pustulosa generalizada","L402":"Acrodermatite continua de Hallopeau","L403":"Pustulose palmoplantar","L404":"Psoriase gutata","L405":"Artrite psoriatica - artropatia psoriatica","L408":"Outras psoriases","L409":"Psoriase nao especificada",
"L200":"Prurigo de Besnier - dermatite atopica","L208":"Outras dermatites atopicas","L209":"Dermatite atopica nao especificada",
"L930":"Lupus eritematoso discoide","L931":"Lupus eritematoso cutaneo subagudo","L932":"Outros lupus eritematosos localizados","L939":"Lupus eritematoso nao especificado",
// EXPANSÃO — Ginecologia/Obstetricia
"N800":"Endometriose uterina - adenomiose","N801":"Endometriose ovariana","N802":"Endometriose tubaria","N803":"Endometriose pelvica","N804":"Endometriose retovaginal","N805":"Endometriose intestinal","N806":"Endometriose cicatriz cutanea","N808":"Outras endometrioses","N809":"Endometriose nao especificada",
"O140":"Pre-eclampsia leve a moderada","O141":"Pre-eclampsia grave","O142":"HELLP - Hemolise enzimas hepaticas elevadas e plaquetopenia","O149":"Pre-eclampsia nao especificada",
"O240":"Diabetes preexistente tipo 1 na gravidez","O241":"Diabetes preexistente tipo 2 na gravidez","O242":"Diabetes preexistente relacionada com desnutricao","O243":"Diabetes preexistente nao especificada","O244":"Diabetes mellitus gestacional","O249":"Diabetes na gravidez nao especificado",
// EXPANSÃO — Psiquiatria detalhada
"F200":"Esquizofrenia paranoide","F201":"Esquizofrenia hebefrenica - desorganizada","F202":"Esquizofrenia catatonica","F203":"Esquizofrenia indiferenciada","F204":"Depressao pos-esquizofrenica","F205":"Esquizofrenia residual","F206":"Esquizofrenia simples","F208":"Outras esquizofrenias","F209":"Esquizofrenia nao especificada",
"F310":"TAB - Transtorno afetivo bipolar episodio hipomaniaco","F311":"TAB episodio maniaco sem psicose","F312":"TAB episodio maniaco com psicose","F313":"TAB episodio depressivo leve ou moderado","F314":"TAB episodio depressivo grave sem psicose","F315":"TAB episodio depressivo grave com psicose","F316":"TAB episodio misto","F317":"TAB em remissao","F318":"Outros transtornos bipolares","F319":"Transtorno bipolar nao especificado",
"F320":"Depressao leve","F321":"Depressao moderada","F322":"Depressao grave sem sintomas psicoticos","F323":"Depressao grave com sintomas psicoticos","F328":"Outros episodios depressivos","F329":"Episodio depressivo nao especificado",
"F410":"Transtorno de panico - sindrome do panico","F411":"TAG - Transtorno de ansiedade generalizada","F412":"Transtorno misto ansioso e depressivo","F419":"Transtorno ansioso nao especificado",
"F430":"Reacao aguda ao estresse","F431":"TEPT - Transtorno de estresse pos-traumatico","F432":"Transtorno de adaptacao com humor depressivo","F433":"Transtorno de adaptacao com ansiedade","F438":"Outras reacoes a estresse grave","F439":"Reacao a estresse nao especificada",
"F600":"Transtorno paranoide de personalidade","F601":"Transtorno esquizoide de personalidade","F602":"Transtorno dissocial de personalidade - psicopatia","F603":"Transtorno borderline - personalidade emocionalmente instavel","F604":"Transtorno histrionico de personalidade","F605":"Transtorno obsessivo-compulsivo de personalidade","F606":"Transtorno ansioso de personalidade - personalidade evitativa","F607":"Transtorno dependente de personalidade","F608":"Outros transtornos de personalidade","F609":"Transtorno de personalidade nao especificado",
// EXPANSÃO — Ortopedia/Reumatologia
"M170":"Gonartrose primaria bilateral - artrose bilateral dos joelhos","M171":"Gonartrose primaria unilateral","M172":"Gonartrose pos-traumatica bilateral","M173":"Gonartrose pos-traumatica unilateral","M174":"Outras gonartroses secundarias","M179":"Gonartrose nao especificada",
"M160":"Coxartrose primaria bilateral - artrose bilateral do quadril","M161":"Coxartrose primaria unilateral","M162":"Coxartrose pos-traumatica bilateral","M163":"Coxartrose pos-traumatica unilateral","M164":"Coxartrose resultante de displasia bilateral","M165":"Coxartrose resultante de displasia unilateral","M166":"Outras coxartroses secundarias bilaterais","M167":"Outras coxartroses secundarias unilaterais","M169":"Coxartrose nao especificada",
"M510":"Hernia de disco lombar com mielopatia","M511":"Hernia de disco lombar com radiculopatia - lombociatalgia","M512":"Outros deslocamentos dos discos intervertebrais","M513":"Outras degeneracoes dos discos intervertebrais","M514":"Nodulos de Schmorl","M515":"Outras degeneracoes discais","M518":"Outros transtornos especificados dos discos","M519":"Transtorno disco intervertebral nao especificado",
"M750":"Capsulite adesiva do ombro - ombro congelado","M751":"Sindrome do manguito rotador","M752":"Tendinite bicipital","M753":"Tendinite calcificante do ombro","M754":"Sindrome do impacto subacromial","M755":"Bursite do ombro","M758":"Outras lesoes do ombro","M759":"Lesao do ombro nao especificada",
"M810":"Osteoporose pos-menopausica","M811":"Osteoporose por ooforectomia","M812":"Osteoporose por imobilizacao","M813":"Osteoporose por sindrome de ma-absorcao","M814":"Osteoporose induzida por drogas - osteoporose por corticoide","M815":"Osteoporose idiopatica","M816":"Osteoporose localizada","M818":"Outras osteoporoses","M819":"Osteoporose nao especificada",
// Codigos Z especificos
"Z001":"Exame periodico de saude - check-up anual","Z008":"Exame geral adulto","Z009":"Consulta de rotina nao especificada",
"Z034":"Observacao por suspeita de infarto","Z035":"Observacao por suspeita de doenca cardiovascular","Z038":"Observacao por suspeita de outras doencas",
"Z120":"Rastreamento de tumor maligno do estomago","Z121":"Rastreamento de tumor do intestino","Z122":"Rastreamento de tumor maligno do colo do utero","Z123":"Rastreamento de tumor maligno da mama","Z124":"Rastreamento de tumor maligno do colo do intestino","Z126":"Rastreamento de tumor maligno da prostata","Z128":"Rastreamento de outros tumores malignos","Z129":"Rastreamento de tumor maligno nao especificado",
"Z720":"Tabagismo ativo","Z721":"Etilismo - uso nocivo de alcool","Z722":"Uso de drogas ilicitas","Z723":"Falta de exercicio fisico","Z724":"Dieta e habitos alimentares inadequados","Z725":"Alto nivel de risco sexual","Z726":"Jogo patologico"
};

const CID_LIST = Object.entries(CID).map(([code,desc])=>({code,desc}));

function norm(s){
  return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').trim();
}

export default async function handler(req,res){
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Cache-Control','public,max-age=86400');
  if(req.method==='OPTIONS') return res.status(200).end();
  const q=(req.method==='GET'?req.query.q:req.body?.q)||'';
  if(!q||q.length<2) return res.status(200).json({results:[]});
  const qn=norm(q);
  const qUp=q.toUpperCase().replace(/\./g,'').trim();
  const priority=[],secondary=[];
  for(const item of CID_LIST){
    const c=item.code.replace(/\./g,'');
    if(c.startsWith(qUp)){priority.push(item);if(priority.length>=8)break;}
    else if(priority.length+secondary.length<20&&norm(item.desc).includes(qn))secondary.push(item);
  }
  return res.status(200).json({results:[...priority,...secondary].slice(0,10)});
}
